# Generated by Django 3.0.8 on 2020-07-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('uid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=32)),
                ('register_time', models.DateTimeField(auto_now_add=True)),
                ('modified_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'usermodel',
                'ordering': ['username', 'password', 'register_time', 'uid', 'modified_time'],
            },
        ),
    ]
