# Generated by Django 3.0.8 on 2020-07-28 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublisherModel',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=32)),
            ],
            options={
                'db_table': 'publisher',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('bid', models.AutoField(primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=32)),
                ('pub', models.ForeignKey(blank=True, db_column='pid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='App.PublisherModel')),
            ],
            options={
                'db_table': 'book',
            },
        ),
    ]
